In [1]:
import pandas as pd
import openpyxl
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"
import datetime as dt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rc
plt.rcParams["axes.unicode_minus"] = False 
rc("font", family="Arial Unicode MS") # Windows: Malgun Gothic 
# %matplotlib inline 
get_ipython().run_line_magic("matplotlib", "inline")

In [2]:
df = pd.read_csv("버스_출근퇴근_총_인원정보(최종).csv", index_col=0)
df

/var/folders/hr/y8znbyhd4058w4d5l14qqsv80000gn/T/ipykernel_35427/2041198187.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("버스_출근퇴근_총_인원정보(최종).csv", index_col=0)

,사용년월,노선번호,노선명,표준버스정류장ID,역명,경도,위도,출근,퇴근,총 이동량
0,201801,100,100번(하계동~용산구청),100000002,창경궁.서울대학교병원,126.996566,37.579183,2224,384,2608
1,201801,100,100번(하계동~용산구청),100000003,명륜3가.성대입구,126.998340,37.582671,1893,770,2663
2,201801,100,100번(하계동~용산구청),100000005,혜화동로터리,127.001744,37.586243,1491,281,1772
3,201801,100,100번(하계동~용산구청),100000102,원남동,126.997338,37.574533,2400,1424,3824
4,201801,100,100번(하계동~용산구청),100000108,종로5가.효제동,127.002230,37.574500,173,466,639
...,...,...,...,...,...,...,...,...,...,...
1834733,202112,중랑02,중랑02(진로아파트~한신아파트),106900025,새마을금고,127.097322,37.589095,729,119,848
1834734,202112,중랑02,중랑02(진로아파트~한신아파트),106900026,진주빌라.바다약국,127.100663,37.587773,638,9,647
1834735,202112,중랑02,중랑02(진로아파트~한신아파트),106900028,서일대정문,127.096023,37.587710,1807,32,1839
1834736,202112,중랑02,중랑02(진로아파트~한신아파트),106900029,서일대정문,127.095968,37.588072,150,967,1117
1834737,202112,중랑02,중랑02(진로아파트~한신아파트),106900030,IBK기업은행면목동지점,127.085010,37.587655,1561,174,1735

In [17]:
df_remove_2101 = df[df['사용년월'] != 202101]
df_2101 = df[df['사용년월'] == 202101]

In [18]:
df_2101

,사용년월,노선번호,노선명,표준버스정류장ID,역명,경도,위도,출근,퇴근,총 이동량
1373733,202101,0017,0017번(청암동~이촌동),102000001,한강대교북단.LG유플러스,126.963192,37.524090,7598,2790,10388
1373734,202101,0017,0017번(청암동~이촌동),102000003,신용산역,126.966207,37.527293,4972,1856,6828
1373735,202101,0017,0017번(청암동~이촌동),102000029,한강대교북단,126.963934,37.525290,1842,2848,4690
1373736,202101,0017,0017번(청암동~이촌동),102000153,용문시장,126.960715,37.536623,724,1850,2574
1373737,202101,0017,0017번(청암동~이촌동),102000154,용문시장,126.961360,37.535979,1080,944,2024
...,...,...,...,...,...,...,...,...,...,...
1411986,202101,중랑02,중랑02(진로아파트~한신아파트),106900025,새마을금고,127.097322,37.589095,1500,228,1728
1411987,202101,중랑02,중랑02(진로아파트~한신아파트),106900026,진주빌라.바다약국,127.100663,37.587773,1184,28,1212
1411988,202101,중랑02,중랑02(진로아파트~한신아파트),106900028,서일대정문,127.096023,37.587710,996,60,1056
1411989,202101,중랑02,중랑02(진로아파트~한신아파트),106900029,서일대정문,127.095968,37.588072,280,862,1142
1411990,202101,중랑02,중랑02(진로아파트~한신아파트),106900030,IBK기업은행면목동지점,127.085010,37.587655,2470,136,2606

In [19]:
df_2101['출근'] = df_2101['출근']//2
df_2101['퇴근'] = df_2101['퇴근']//2
df_2101['총 이동량'] = df_2101['총 이동량']//2

/var/folders/hr/y8znbyhd4058w4d5l14qqsv80000gn/T/ipykernel_35427/560195320.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2101['출근'] = df_2101['출근']//2
/var/folders/hr/y8znbyhd4058w4d5l14qqsv80000gn/T/ipykernel_35427/560195320.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2101['퇴근'] = df_2101['퇴근']//2
/var/folders/hr/y8znbyhd4058w4d5l14qqsv80000gn/T/ipykernel_35427/560195320.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2101['총 이동량'] = df_2101['총 이동량']//2

In [20]:
df_2101

,사용년월,노선번호,노선명,표준버스정류장ID,역명,경도,위도,출근,퇴근,총 이동량
1373733,202101,0017,0017번(청암동~이촌동),102000001,한강대교북단.LG유플러스,126.963192,37.524090,3799,1395,5194
1373734,202101,0017,0017번(청암동~이촌동),102000003,신용산역,126.966207,37.527293,2486,928,3414
1373735,202101,0017,0017번(청암동~이촌동),102000029,한강대교북단,126.963934,37.525290,921,1424,2345
1373736,202101,0017,0017번(청암동~이촌동),102000153,용문시장,126.960715,37.536623,362,925,1287
1373737,202101,0017,0017번(청암동~이촌동),102000154,용문시장,126.961360,37.535979,540,472,1012
...,...,...,...,...,...,...,...,...,...,...
1411986,202101,중랑02,중랑02(진로아파트~한신아파트),106900025,새마을금고,127.097322,37.589095,750,114,864
1411987,202101,중랑02,중랑02(진로아파트~한신아파트),106900026,진주빌라.바다약국,127.100663,37.587773,592,14,606
1411988,202101,중랑02,중랑02(진로아파트~한신아파트),106900028,서일대정문,127.096023,37.587710,498,30,528
1411989,202101,중랑02,중랑02(진로아파트~한신아파트),106900029,서일대정문,127.095968,37.588072,140,431,571
1411990,202101,중랑02,중랑02(진로아파트~한신아파트),106900030,IBK기업은행면목동지점,127.085010,37.587655,1235,68,1303

In [23]:
df_clean = pd.concat([df_remove_2101,df_2101]).sort_values('사용년월')

In [24]:
df_clean.to_csv("버스_출근퇴근_총_인원정보_2101수정완료.csv")